keep single build and run scripts for triton-san

diff --git a/triton-san/template/triton-san.in b/triton-san/template/triton-san.in
--- a/triton-san/template/triton-san.in
+++ b/triton-san/template/triton-san.in
@@ -1,22 +1,47 @@
-# executes a triton program with sanitizers enabled/disabled
-# assume that source setup_runtime_for_sanitizers was run before this
-# use LLVM_BINARY_DIR to obtain the locations of the .so files used for LD_PRELOAD
+# Executes a triton program with triton-san
+
+#!/bin/bash
+set -e
+
+function usage {
+  echo "Usage: triton-san <sanitizer type> <path to trtion program>."
+  echo "<sanitizer type>:"
+  echo "  \"asan\": to detect buffer overflows" 
+  echo "  \"tsan\": to detect data races"
+  echo ""
+  echo "Example: triton-san asan ./my_triton_program.py"
+}
+
+ROOT="@ROOT@"
+TRITON_SHARED_OPT_PATH="@TRITON_SHARED_OPT_PATH@"
+VENV_PATH="@VENV_PATH@"
+LLVM_INSTALL_DIR="@LLVM_INSTALL_DIR@"
 
 if [ "$#" -eq 0 ]; then
-    echo "Usage: $0 <sanitizer type> python program.py. <sanitizer type> can be \"asan\", \"tsan\""
+    usage
     exit 1
 fi
 
 sanitizer_type=$1
 
 if [ "$sanitizer_type" != "asan" ] && [ "$sanitizer_type" != "tsan" ]; then
-    echo "Error: Unsupported <sanitizer type> $sanitizer_type. Usage: $0 <sanitizer type> python program.py. <sanitizer type> can be \"asan\", \"tsan\""
+    echo "Error: Unsupported <sanitizer type> $sanitizer_type."
+    echo ""
+    usage
     exit 1
 fi
 
 env_args=""
 
-llvm_install_dir="$(dirname "${LLVM_BINARY_DIR}")"
+llvm_install_dir="${LLVM_INSTALL_DIR}"
+
+# set up the virtual environment and LLVM
+triton_shared_opt_path="${TRITON_SHARED_OPT_PATH}"
+
+. "${VENV_PATH}/bin/activate"
+export TRITON_SHARED_OPT_PATH="$triton_shared_opt_path"
+export LLVM_BINARY_DIR="${LLVM_INSTALL_DIR}/bin"
+export PATH="${LLVM_INSTALL_DIR}/bin:${PATH}"
 
 if [ "${sanitizer_type}" = "asan" ]; then
     # find path to asan shared library
@@ -35,7 +60,8 @@ if [ "${sanitizer_type}" = "asan" ]; then
         exit 1
     fi
 
-    env_args="LD_PRELOAD=\"$asan_dir\" \
+    env_args="\
+LD_PRELOAD=\"$asan_dir\" \
 TRITON_ALWAYS_COMPILE=1 \
 TRITON_SHARED_SANITIZER_TYPE=\"asan\" \
 ASAN_OPTIONS=\"detect_leaks=0\""
@@ -74,19 +100,14 @@ elif [ "${sanitizer_type}" = "tsan" ]; then
         echo "$archer_dir"
         exit 1
     fi
+    
+    SUPPRESSION_FILE="${ROOT}/tsan_suppression.txt"
 
-    # make new suppression.txt file if it doesn't exist already
-    if [ ! -f "suppression.txt" ]; then
-        echo "called_from_lib:libomp.so
-called_from_lib:libtorch_python.so
-called_from_lib:libtorch_cpu.so
-called_from_lib:libtorch_cuda.so" > "./suppression.txt"
-    fi
-
-    env_args="LD_PRELOAD=\"$tsan_dir\" \
+    env_args="\
+LD_PRELOAD=\"$tsan_dir\" \
 TRITON_ALWAYS_COMPILE=1 \
 TRITON_SHARED_SANITIZER_TYPE=\"tsan\" \
-TSAN_OPTIONS=\"ignore_noninstrumented_modules=0:suppressions=suppression.txt\" \
+TSAN_OPTIONS=\"ignore_noninstrumented_modules=0:report_mutex_bugs=0:suppressions=${SUPPRESSION_FILE}\" \
 OMP_NUM_THREADS=16 \
 OMP_TOOL_LIBRARIES=\"$archer_dir\" \
 ARCHER_OPTIONS=\"verbose=1\""
@@ -96,5 +117,5 @@ ARCHER_OPTIONS=\"verbose=1\""
 fi
 
 # invoke python function
-echo "Running command: ${env_args} $*"
-eval "${env_args} $*"
+echo "Running command: ${env_args} python $*"
+eval "${env_args} python $*"
